import PDFDocument from 'pdfkit';
import { supabase } from '../db/supabase.js';
const money=(n:number)=>'$'+Number(n||0).toFixed(2);
export async function generarProformaPdf(id:string):Promise<Buffer>{
 const {data:p,error}=await supabase.from('proformas').select('*,clientes(*),emisores(*)').eq('id',id).single();if(error||!p)throw new Error(error?.message||'Proforma no encontrada.');
 const {data:items,error:ie}=await supabase.from('proforma_items').select('*').eq('proforma_id',id).order('created_at',{ascending:true});if(ie)throw new Error(ie.message);
 const doc=new PDFDocument({size:'A4',margin:36});const chunks:Buffer[]=[];doc.on('data',c=>chunks.push(c));const done=new Promise<Buffer>(r=>doc.on('end',()=>r(Buffer.concat(chunks))));const e:any=p.emisores||{},c:any=p.clientes||{},w=doc.page.width-72;
 doc.fillColor('#0f2747').fontSize(16).font('Helvetica-Bold').text(e.razon_social||e.nombre_comercial||'CONTSERTRIB',36,36,{width:330});doc.fillColor('#334155').fontSize(9).font('Helvetica').text(e.nombre_comercial||'',36,58).text(e.direccion_matriz||'',36,72).text(`RUC: ${e.ruc||''}`,36,86);
 doc.fillColor('#0f2747').fontSize(17).font('Helvetica-Bold').text('COTIZACIÓN / PROFORMA',360,42,{width:200,align:'right'}).fontSize(10).text(`No. ${p.numero_proforma||''}`,360,68,{width:200,align:'right'}).font('Helvetica').text(`Emisión: ${p.fecha_emision||''}`,360,83,{width:200,align:'right'}).text(`Válida hasta: ${p.fecha_validez||''}`,360,98,{width:200,align:'right'});
 let y=130;doc.roundedRect(36,y,w,58,6).fill('#f8fafc').stroke('#e2e8f0');doc.fillColor('#334155').fontSize(9).font('Helvetica-Bold').text('CLIENTE',48,y+10).font('Helvetica').text(c.razon_social||'Sin cliente',48,y+25,{width:250}).text(`${c.tipo_identificacion||''} ${c.identificacion||''}`,310,y+25,{width:150}).text(c.direccion||'',48,y+40,{width:400}).text(c.email||'',310,y+40,{width:150});
 y+=76;doc.fillColor('#0f2747').rect(36,y,w,20).fill();doc.fillColor('#fff').fontSize(8).font('Helvetica-Bold').text('DESCRIPCIÓN',44,y+6,{width:250}).text('CANT.',300,y+6,{width:45,align:'right'}).text('P. UNIT.',355,y+6,{width:60,align:'right'}).text('DESC.',425,y+6,{width:55,align:'right'}).text('TOTAL',485,y+6,{width:70,align:'right'});y+=20;doc.fillColor('#111827').font('Helvetica').fontSize(8.5);
 for(const it of items||[]){const desc=String(it.descripcion||'');const qty=Number(it.cantidad||0),pu=Number(it.precio_unitario||0),d=Number(it.descuento||0),tot=qty*pu-d,h=Math.max(14,14*Math.ceil(desc.length/48));doc.text(desc,44,y+4,{width:245,height:h}).text(qty.toFixed(2),300,y+4,{width:45,align:'right'}).text(money(pu),355,y+4,{width:60,align:'right'}).text(money(d),425,y+4,{width:55,align:'right'}).text(money(tot),485,y+4,{width:70,align:'right'});y+=h;doc.moveTo(36,y).lineTo(36+w,y).strokeColor('#e5e7eb').stroke().strokeColor('#000');}
 if(!(items||[]).length){doc.fillColor('#64748b').text('No existen ítems registrados en esta proforma.',44,y+10);y+=30;}y+=14;const subtotal=Number(p.subtotal||0),iva=Number(p.total_iva||p.iva||0),total=Number(p.total||0);doc.fillColor('#334155').font('Helvetica-Bold').text('Subtotal',400,y,{width:80}).font('Helvetica').text(money(subtotal),485,y,{width:70,align:'right'});y+=15;doc.font('Helvetica-Bold').text('IVA',400,y,{width:80}).font('Helvetica').text(money(iva),485,y,{width:70,align:'right'});y+=20;doc.fillColor('#0f2747').roundedRect(390,y,175,28,5).fill();doc.fillColor('#fff').font('Helvetica-Bold').fontSize(11).text('TOTAL '+money(total),400,y+8,{width:155,align:'right'});y+=50;doc.fillColor('#475569').fontSize(8).font('Helvetica').text('Esta proforma/cotización es una oferta comercial y no constituye por sí misma un comprobante electrónico autorizado por el SRI. La factura electrónica se emite por el módulo de comprobantes cuando corresponda.',36,y,{width:w,align:'justify'});y+=32;doc.font('Helvetica-Bold').text('Condiciones comerciales',36,y).font('Helvetica').text('Precios expresados en dólares de los Estados Unidos de América. Vigencia y condiciones según lo acordado con el cliente.',36,y+14,{width:w});doc.end();return done;
}
