import PDFDocument from 'pdfkit';
import { supabase } from '../db/supabase.js';
import { fechaIsoEcuador } from '../utils/fechaEcuador.js';
const money=(n:number)=>'$'+Number(n||0).toFixed(2); const txt=(v:unknown)=>String(v??'').trim();
export async function generarProformaPdf(id:string):Promise<Buffer>{
 const {data:p,error}=await supabase.from('proformas').select('*,clientes(*)').eq('id',id).single(); if(error||!p)throw new Error(error?.message||'Proforma no encontrada.');
 const {data:e,error:ee}=await supabase.from('emisores').select('*').eq('id',p.emisor_id).single(); if(ee||!e)throw new Error(ee?.message||'No se encontró el emisor.');
 const {data:items,error:ie}=await supabase.from('proforma_items').select('*').eq('proforma_id',id); if(ie)throw new Error(ie.message);
 const doc=new PDFDocument({size:'A4',margin:36}); const chunks:Buffer[]=[]; doc.on('data',c=>chunks.push(c)); const done=new Promise<Buffer>(r=>doc.on('end',()=>r(Buffer.concat(chunks)))); const w=doc.page.width-72; const c:any=p.clientes||{};
 const header=()=>{doc.rect(36,28,w,82).fill('#0f2747');doc.fillColor('#fff').font('Helvetica-Bold').fontSize(15).text(txt(e.razon_social)||txt(e.nombre_comercial)||'CONTSERTRIB',50,42,{width:300});doc.font('Helvetica').fontSize(8.5).text(txt(e.nombre_comercial),50,63,{width:300});doc.text('RUC: '+txt(e.ruc),50,77);doc.text(txt(e.direccion_matriz||e.direccion),50,91,{width:300});doc.font('Helvetica-Bold').fontSize(18).text('PROFORMA',390,46,{width:160,align:'right'});doc.font('Helvetica').fontSize(9).text('N.° '+txt(p.numero_proforma),390,70,{width:160,align:'right'}).text('Emisión: '+txt(p.fecha_emision||fechaIsoEcuador()),390,84,{width:160,align:'right'}).text('Válida hasta: '+txt(p.fecha_validez),390,98,{width:160,align:'right'});};
 const footer=()=>doc.fillColor('#64748b').font('Helvetica').fontSize(7).text('CONTSERTRIB FACTURACIÓN · Documento comercial no tributario · No constituye comprobante electrónico autorizado por el SRI.',36,doc.page.height-25,{width:w,align:'center'});
 header(); let y=128; doc.roundedRect(36,y,w,70,7).fill('#f8fafc').stroke('#dbe3ee'); doc.fillColor('#0f2747').font('Helvetica-Bold').fontSize(9).text('DATOS DEL CLIENTE',48,y+10); doc.fillColor('#334155').font('Helvetica-Bold').fontSize(9).text(txt(c.razon_social)||'Sin cliente',48,y+28,{width:270}); doc.font('Helvetica').text(`${txt(c.tipo_identificacion)} ${txt(c.identificacion)}`,330,y+28,{width:100}); doc.text(txt(c.direccion),48,y+45,{width:360}); doc.text(txt(c.email),330,y+45,{width:100}); y+=86;
 const encabezado=()=>{doc.fillColor('#0f2747').rect(36,y,w,21).fill();doc.fillColor('#fff').font('Helvetica-Bold').fontSize(8).text('DESCRIPCIÓN',44,y+7,{width:245}).text('CANT.',300,y+7,{width:45,align:'right'}).text('P. UNIT.',355,y+7,{width:60,align:'right'}).text('DESC.',425,y+7,{width:55,align:'right'}).text('TOTAL',485,y+7,{width:70,align:'right'});y+=21;doc.fillColor('#111827').font('Helvetica').fontSize(8.5);};
 encabezado(); for(const it of items||[]){const desc=txt(it.descripcion)||'—',qty=Number(it.cantidad||0),pu=Number(it.precio_unitario||0),d=Number(it.descuento||0),tot=qty*pu-d,h=Math.max(17,14*Math.ceil(desc.length/48));if(y+h>doc.page.height-70){footer();doc.addPage();header();y=128;encabezado();}doc.text(desc,44,y+5,{width:245,height:h});doc.text(qty.toFixed(2),300,y+5,{width:45,align:'right'});doc.text(money(pu),355,y+5,{width:60,align:'right'});doc.text(money(d),425,y+5,{width:55,align:'right'});doc.text(money(tot),485,y+5,{width:70,align:'right'});y+=h;doc.moveTo(36,y).lineTo(36+w,y).strokeColor('#e5e7eb').stroke().strokeColor('#000');}
 if(!(items||[]).length){doc.fillColor('#64748b').text('No existen ítems registrados.',44,y+8);y+=30;} y+=14; const subtotal=Number(p.subtotal||0),total=Number(p.total||0),iva=Math.max(0,total-subtotal); if(y>doc.page.height-135){footer();doc.addPage();header();y=128;} doc.fillColor('#334155').font('Helvetica-Bold').text('Subtotal',400,y,{width:80}).font('Helvetica').text(money(subtotal),485,y,{width:70,align:'right'});y+=16;doc.font('Helvetica-Bold').text('IVA',400,y,{width:80}).font('Helvetica').text(money(iva),485,y,{width:70,align:'right'});y+=22;doc.fillColor('#0f2747').roundedRect(390,y,175,30,5).fill();doc.fillColor('#fff').font('Helvetica-Bold').fontSize(11).text('TOTAL '+money(total),400,y+9,{width:155,align:'right'});y+=50;doc.fillColor('#334155').font('Helvetica-Bold').fontSize(9).text('CONDICIONES COMERCIALES',36,y);doc.fillColor('#475569').font('Helvetica').fontSize(8).text('Precios expresados en dólares de los Estados Unidos de América. Vigencia y condiciones según lo acordado con el cliente.',36,y+15,{width:w});footer();doc.end();return done;
}
