import type { FastifyInstance } from 'fastify';
import { supabase } from '../db/supabase.js';
import { contabilizarMovimientoBancario } from '../services/tesoreriaContable.js';

const emisor=(req:any)=>String(req.usuarioSesion?.emisorId||'');
export async function registrarRutasBancos(app:FastifyInstance){
 app.get('/contabilidad/bancos',async(req:any,reply)=>{const id=emisor(req);if(!id)return reply.status(401).send({error:'Empresa activa requerida.'});const {data,error}=await supabase.from('cuentas_bancarias').select('id,nombre,banco,numero_mascara,tipo,moneda,cuenta_contable_id,activa').eq('emisor_id',id).order('nombre');if(error)return reply.status(500).send({error:error.message});return reply.send(data||[])});
 app.post('/contabilidad/bancos',async(req:any,reply)=>{const id=emisor(req),b=req.body||{};if(!id)return reply.status(401).send({error:'Empresa activa requerida.'});if(!b.nombre||!b.cuentaContableId)return reply.status(400).send({error:'Nombre y cuenta contable son obligatorios.'});const {data:cuenta}=await supabase.from('plan_cuentas_contables').select('id').eq('id',b.cuentaContableId).eq('emisor_id',id).eq('activa',true).eq('acepta_movimientos',true).maybeSingle();if(!cuenta)return reply.status(422).send({error:'Cuenta contable inválida para la empresa activa.'});const {data,error}=await supabase.from('cuentas_bancarias').insert({emisor_id:id,nombre:String(b.nombre),banco:b.banco||null,numero_mascara:b.numeroMascara||null,tipo:b.tipo||'CORRIENTE',moneda:b.moneda||'USD',cuenta_contable_id:cuenta.id}).select('*').single();if(error)return reply.status(422).send({error:error.message});return reply.status(201).send(data)});
 app.get('/contabilidad/bancos/:id/movimientos',async(req:any,reply)=>{const id=emisor(req);if(!id)return reply.status(401).send({error:'Empresa activa requerida.'});const {data,error}=await supabase.from('movimientos_bancarios').select('*').eq('emisor_id',id).eq('cuenta_bancaria_id',req.params.id).order('fecha',{ascending:false}).limit(1000);if(error)return reply.status(500).send({error:error.message});return reply.send(data||[])});
 app.post('/contabilidad/bancos/:id/movimientos',async(req:any,reply)=>{const id=emisor(req),b=req.body||{};if(!id)return reply.status(401).send({error:'Empresa activa requerida.'});if(!b.fecha||!b.tipo||!b.concepto||Number(b.monto)<=0||!b.idempotencyKey)return reply.status(400).send({error:'Fecha, tipo, concepto, monto e idempotencyKey son obligatorios.'});const {data:bank}=await supabase.from('cuentas_bancarias').select('id').eq('id',req.params.id).eq('emisor_id',id).eq('activa',true).maybeSingle();if(!bank)return reply.status(404).send({error:'Cuenta bancaria no encontrada.'});const row={emisor_id:id,cuenta_bancaria_id:bank.id,fecha:b.fecha,tipo:String(b.tipo).toUpperCase(),concepto:String(b.concepto),referencia:b.referencia||null,monto:Number(b.monto),origen_tipo:b.contrapartidaCuentaId?'CUENTA_CONTABLE':null,origen_id:b.contrapartidaCuentaId||null,idempotency_key:String(b.idempotencyKey)};const {data,error}=await supabase.from('movimientos_bancarios').upsert(row,{onConflict:'emisor_id,idempotency_key',ignoreDuplicates:true}).select('*').maybeSingle();if(error)return reply.status(422).send({error:error.message});if(data)return reply.status(201).send(data);const existente=await supabase.from('movimientos_bancarios').select('*').eq('emisor_id',id).eq('idempotency_key',b.idempotencyKey).single();return reply.send(existente.data)});
 app.post('/contabilidad/bancos/movimientos/:id/contabilizar',async(req:any,reply)=>{const id=emisor(req);if(!id)return reply.status(401).send({error:'Empresa activa requerida.'});try{return reply.send(await contabilizarMovimientoBancario(req.params.id,id,req.usuarioSesion?.userId))}catch(e){return reply.status(422).send({error:e instanceof Error?e.message:String(e)})}});
}
