import type { FastifyInstance } from 'fastify';
import { supabase } from '../db/supabase.js';
import { asegurarPlanBase, contabilizarVenta, obtenerBalanza, contabilizarCxP, contabilizarPagoCxP, contabilizarCxC, contabilizarCobroCxC } from '../services/motorContable.js';

export async function registrarRutasContabilidad(app: FastifyInstance){
  app.get<{Querystring:{emisorId?:string}}>("/contabilidad/plan", async (req,reply)=>{const id=String(req.query.emisorId||'');if(!id)return reply.status(400).send({error:'emisorId requerido'});await asegurarPlanBase(id);const {data,error}=await supabase.from('plan_cuentas_contables').select('*').eq('emisor_id',id).eq('activa',true).order('codigo');if(error)return reply.status(500).send({error:error.message});return reply.send({cuentas:data??[]});});
  app.get<{Querystring:{emisorId?:string;desde?:string;hasta?:string}}>("/contabilidad/balanza", async(req,reply)=>{const id=String(req.query.emisorId||'');if(!id)return reply.status(400).send({error:'emisorId requerido'});try{return reply.send({cuentas:await obtenerBalanza(id,req.query.desde,req.query.hasta)});}catch(e){return reply.status(500).send({error:e instanceof Error?e.message:String(e)});}});
  app.get<{Querystring:{emisorId?:string;desde?:string;hasta?:string}}>("/contabilidad/diario", async(req,reply)=>{const id=String(req.query.emisorId||'');if(!id)return reply.status(400).send({error:'emisorId requerido'});let q=supabase.from('asientos_contables').select('*,asiento_lineas_contables(*,plan_cuentas_contables(codigo,nombre))').eq('emisor_id',id).order('fecha',{ascending:false}).order('created_at',{ascending:false});if(req.query.desde)q=q.gte('fecha',req.query.desde);if(req.query.hasta)q=q.lte('fecha',req.query.hasta);const {data,error}=await q.limit(300);if(error)return reply.status(500).send({error:error.message});return reply.send({asientos:data??[]});});
  app.post<{Body:{emisorId?:string;fecha?:string;concepto?:string;referencia?:string;lineas?:Array<{codigo:string;descripcion?:string;debe?:number;haber?:number}>}}>("/contabilidad/asientos",async(req,reply)=>{const b=req.body||{};const id=String(b.emisorId||'');if(!id||!b.fecha||!b.concepto||!Array.isArray(b.lineas)||!b.lineas.length)return reply.status(400).send({error:'Datos incompletos.'});try{await asegurarPlanBase(id);const lineas=b.lineas.map(l=>({codigo:l.codigo,descripcion:l.descripcion||b.concepto,debe:Number(l.debe||0),haber:Number(l.haber||0)}));const debe=lineas.reduce((s,x)=>s+x.debe,0),haber=lineas.reduce((s,x)=>s+x.haber,0);if(Math.abs(debe-haber)>0.01||debe<=0)return reply.status(422).send({error:`El asiento no cuadra. Debe ${debe.toFixed(2)} / Haber ${haber.toFixed(2)}`});const {data,error}=await supabase.rpc('crear_asiento_contable_atomico',{p_emisor_id:id,p_fecha:b.fecha,p_tipo:'MANUAL',p_concepto:b.concepto,p_referencia:b.referencia||null,p_origen_tipo:null,p_origen_id:null,p_created_by:req.usuarioSesion?.userId||null,p_lineas:lineas});if(error)return reply.status(422).send({error:error.message});return reply.send({ok:true,asientoId:data});}catch(e){return reply.status(500).send({error:e instanceof Error?e.message:String(e)});}});
  app.post<{Params:{id:string}}>("/contabilidad/cxp/:id/contabilizar",async(req,reply)=>{try{return reply.send({ok:true,asiento:await contabilizarCxP(req.params.id,req.usuarioSesion?.userId)});}catch(e){return reply.status(422).send({error:e instanceof Error?e.message:String(e)});}});
  app.post<{Params:{cuentaId:string; pagoId:string}}>("/contabilidad/cxp/:cuentaId/pagos/:pagoId/contabilizar",async(req,reply)=>{try{return reply.send({ok:true,asiento:await contabilizarPagoCxP(req.params.cuentaId,req.params.pagoId,req.usuarioSesion?.userId)});}catch(e){return reply.status(422).send({error:e instanceof Error?e.message:String(e)});}});
  app.post<{Params:{id:string}}>("/contabilidad/cxc/:id/contabilizar",async(req,reply)=>{try{return reply.send({ok:true,asiento:await contabilizarCxC(req.params.id,req.usuarioSesion?.userId)});}catch(e){return reply.status(422).send({error:e instanceof Error?e.message:String(e)});}});
  app.post<{Params:{cuentaId:string;pagoId:string}}>("/contabilidad/cxc/:cuentaId/pagos/:pagoId/contabilizar",async(req,reply)=>{try{return reply.send({ok:true,asiento:await contabilizarCobroCxC(req.params.cuentaId,req.params.pagoId,req.usuarioSesion?.userId)});}catch(e){return reply.status(422).send({error:e instanceof Error?e.message:String(e)});}});
  app.get<{Querystring:{emisorId?:string;desde?:string;hasta?:string}}>("/contabilidad/estado-resultados",async(req,reply)=>{try{const b=await obtenerBalanza(String(req.query.emisorId||''),req.query.desde,req.query.hasta);const ingresos=b.filter(x=>x.tipo==='INGRESO').map(x=>({...x,saldo:Math.abs(x.saldo)}));const gastos=b.filter(x=>['COSTO','GASTO'].includes(x.tipo)).map(x=>({...x,saldo:Math.abs(x.saldo)}));const totalIngresos=ingresos.reduce((s,x)=>s+x.saldo,0),totalGastos=gastos.reduce((s,x)=>s+x.saldo,0);return reply.send({ingresos,gastos,totalIngresos,totalGastos,resultado:totalIngresos-totalGastos});}catch(e){return reply.status(500).send({error:e instanceof Error?e.message:String(e)});}});
  app.get<{Querystring:{emisorId?:string;desde?:string;hasta?:string}}>("/contabilidad/balance-general",async(req,reply)=>{try{const b=await obtenerBalanza(String(req.query.emisorId||''),req.query.desde,req.query.hasta);const act=b.filter(x=>x.tipo==='ACTIVO'),pas=b.filter(x=>x.tipo==='PASIVO'),pat=b.filter(x=>x.tipo==='PATRIMONIO');return reply.send({activos:act,pasivos:pas,patrimonio:pat,totalActivos:act.reduce((s,x)=>s+Math.abs(x.saldo),0),totalPasivos:pas.reduce((s,x)=>s+Math.abs(x.saldo),0),totalPatrimonio:pat.reduce((s,x)=>s+Math.abs(x.saldo),0)});}catch(e){return reply.status(500).send({error:e instanceof Error?e.message:String(e)});}});
  app.get<{Querystring:{emisorId?:string}}>("/contabilidad/periodos",async(req,reply)=>{const id=String(req.query.emisorId||'');if(!id)return reply.status(400).send({error:'emisorId requerido'});const {data,error}=await supabase.from('periodos_contables').select('*').eq('emisor_id',id).order('periodo',{ascending:false}).limit(24);if(error)return reply.status(500).send({error:error.message});return reply.send({periodos:data||[]});});
  app.post<{Body:{emisorId?:string;periodo?:string}}>("/contabilidad/periodos/cerrar",async(req,reply)=>{const b=req.body||{};if(!b.emisorId||!b.periodo)return reply.status(400).send({error:'emisorId y periodo requeridos'});const {error}=await supabase.rpc('cerrar_periodo_contable',{p_emisor_id:b.emisorId,p_periodo:b.periodo,p_user_id:req.usuarioSesion?.userId||null});if(error)return reply.status(422).send({error:error.message});return reply.send({ok:true});});
  app.post<{Params:{id:string}}>("/contabilidad/comprobantes/:id/contabilizar",async(req,reply)=>{try{return reply.send({ok:true,asiento:await contabilizarVenta(req.params.id,req.usuarioSesion?.userId)});}catch(e){return reply.status(422).send({error:e instanceof Error?e.message:String(e)});}});
  app.get<{Querystring:{emisorId?:string}}>("/contabilidad/resumen",async(req,reply)=>{const id=String(req.query.emisorId||'');if(!id)return reply.status(400).send({error:'emisorId requerido'});try{const bal=await obtenerBalanza(id);const suma=(tipos:string[])=>bal.filter(x=>tipos.includes(x.tipo)).reduce((s,x)=>s+x.saldo,0);const ingresos=-suma(['INGRESO']);const gastos=suma(['COSTO','GASTO']);const activos=suma(['ACTIVO']);const pasivos=-suma(['PASIVO']);const patrimonio=-suma(['PATRIMONIO']);const resultado=ingresos-gastos;const {count:descuadrados}=await supabase.from('asientos_contables').select('id',{count:'exact',head:true}).eq('emisor_id',id).neq('diferencia',0);return reply.send({activos, pasivos, patrimonio, ingresos, gastos, resultado, asientosDescuadrados:descuadrados||0, cuentas:bal});}catch(e){return reply.status(500).send({error:e instanceof Error?e.message:String(e)});}});
}
