import type { FastifyInstance } from 'fastify';
import { supabase } from '../db/supabase.js';
import { asegurarPlanBase, contabilizarVenta, obtenerBalanza, CUENTAS_BASE } from '../services/motorContable.js';

export async function registrarRutasContabilidad(app: FastifyInstance){
  app.get<{Querystring:{emisorId?:string}}>("/contabilidad/plan", async (req,reply)=>{const id=String(req.query.emisorId||'');if(!id)return reply.status(400).send({error:'emisorId requerido'});await asegurarPlanBase(id);const {data,error}=await supabase.from('plan_cuentas_contables').select('*').eq('emisor_id',id).eq('activa',true).order('codigo');if(error)return reply.status(500).send({error:error.message});return reply.send({cuentas:data??[]});});
  app.get<{Querystring:{emisorId?:string;desde?:string;hasta?:string}}>("/contabilidad/balanza", async(req,reply)=>{const id=String(req.query.emisorId||'');if(!id)return reply.status(400).send({error:'emisorId requerido'});try{return reply.send({cuentas:await obtenerBalanza(id,req.query.desde,req.query.hasta)});}catch(e){return reply.status(500).send({error:e instanceof Error?e.message:String(e)});}});
  app.get<{Querystring:{emisorId?:string;desde?:string;hasta?:string}}>("/contabilidad/diario", async(req,reply)=>{const id=String(req.query.emisorId||'');if(!id)return reply.status(400).send({error:'emisorId requerido'});let q=supabase.from('asientos_contables').select('*,asiento_lineas_contables(*,plan_cuentas_contables(codigo,nombre))').eq('emisor_id',id).order('fecha',{ascending:false}).order('created_at',{ascending:false});if(req.query.desde)q=q.gte('fecha',req.query.desde);if(req.query.hasta)q=q.lte('fecha',req.query.hasta);const {data,error}=await q.limit(300);if(error)return reply.status(500).send({error:error.message});return reply.send({asientos:data??[]});});
  app.post<{Body:{emisorId?:string;fecha?:string;concepto?:string;referencia?:string;lineas?:Array<{codigo:string;descripcion?:string;debe?:number;haber?:number}>}}>("/contabilidad/asientos",async(req,reply)=>{const b=req.body||{};const id=String(b.emisorId||'');if(!id||!b.fecha||!b.concepto||!Array.isArray(b.lineas)||!b.lineas.length)return reply.status(400).send({error:'Datos incompletos.'});try{await asegurarPlanBase(id);const lineas=[];for(const l of b.lineas){const {data:c}=await supabase.from('plan_cuentas_contables').select('id').eq('emisor_id',id).eq('codigo',l.codigo).single();if(!c)throw new Error(`Cuenta ${l.codigo} no existe.`);lineas.push({cuenta_id:c.id,descripcion:l.descripcion||b.concepto,debe:Number(l.debe||0),haber:Number(l.haber||0)});}const debe=lineas.reduce((s,x)=>s+x.debe,0),haber=lineas.reduce((s,x)=>s+x.haber,0);if(Math.abs(debe-haber)>0.01)return reply.status(422).send({error:`El asiento no cuadra. Diferencia ${(debe-haber).toFixed(2)}`});const {data:a,error:ae}=await supabase.from('asientos_contables').insert({emisor_id:id,fecha:b.fecha,tipo:'MANUAL',concepto:b.concepto,referencia:b.referencia||null,estado:'CONTABILIZADO',total_debe:debe,total_haber:haber,diferencia:debe-haber,created_by:req.usuarioSesion?.userId||null}).select('*').single();if(ae||!a)throw new Error(ae?.message||'No se creó el asiento.');const {error:le}=await supabase.from('asiento_lineas_contables').insert(lineas.map(x=>({...x,asiento_id:a.id})));if(le)throw new Error(le.message);return reply.send({ok:true,asiento:a});}catch(e){return reply.status(500).send({error:e instanceof Error?e.message:String(e)});}});
  app.post<{Params:{id:string}}>("/contabilidad/comprobantes/:id/contabilizar",async(req,reply)=>{try{return reply.send({ok:true,asiento:await contabilizarVenta(req.params.id,req.usuarioSesion?.userId)});}catch(e){return reply.status(422).send({error:e instanceof Error?e.message:String(e)});}});
  app.get<{Querystring:{emisorId?:string}}>("/contabilidad/resumen",async(req,reply)=>{const id=String(req.query.emisorId||'');if(!id)return reply.status(400).send({error:'emisorId requerido'});try{const bal=await obtenerBalanza(id);const suma=(tipos:string[])=>bal.filter(x=>tipos.includes(x.tipo)).reduce((s,x)=>s+x.saldo,0);const ingresos=-suma(['INGRESO']);const gastos=suma(['COSTO','GASTO']);const activos=suma(['ACTIVO']);const pasivos=-suma(['PASIVO']);const patrimonio=-suma(['PATRIMONIO']);const resultado=ingresos-gastos;const {count:descuadrados}=await supabase.from('asientos_contables').select('id',{count:'exact',head:true}).eq('emisor_id',id).neq('diferencia',0);return reply.send({activos, pasivos, patrimonio, ingresos, gastos, resultado, asientosDescuadrados:descuadrados||0, cuentas:bal});}catch(e){return reply.status(500).send({error:e instanceof Error?e.message:String(e)});}});
}
