import type { FastifyInstance } from 'fastify';
import { supabase } from '../db/supabase.js';
import { generarExcelDesdeFilas, parsearExcel } from '../services/excel.js';

const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function str(v:unknown){return String(v??'').trim();}

export async function registrarRutasImportacionDatos(app:FastifyInstance){
  app.get('/clientes/exportar',async(req:any,reply)=>{const id=str(req.query.emisorId);if(!id)return reply.status(400).send({error:'emisorId requerido'});const {data,error}=await supabase.from('clientes').select('tipo_identificacion,identificacion,razon_social,email,telefono,direccion').eq('emisor_id',id).order('razon_social');if(error)return reply.status(500).send({error:error.message});const b=await generarExcelDesdeFilas('Clientes',[{clave:'tipo_identificacion',etiqueta:'Tipo identificación'},{clave:'identificacion',etiqueta:'Identificación'},{clave:'razon_social',etiqueta:'Razón social / nombres'},{clave:'email',etiqueta:'Correo electrónico'},{clave:'telefono',etiqueta:'Teléfono'},{clave:'direccion',etiqueta:'Dirección'}],data||[] as any);reply.header('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').header('Content-Disposition','attachment; filename="clientes.xlsx"');return reply.send(b);});
  app.post('/clientes/importar',async(req:any,reply)=>{const id=str(req.body?.emisorId),b64=str(req.body?.archivoBase64);if(!id||!b64)return reply.status(400).send({error:'Emisor y archivo son obligatorios.'});let rows:any[];try{rows=await parsearExcel(Buffer.from(b64,'base64'));}catch(e){return reply.status(400).send({error:'No se pudo leer el Excel.',detalle:String(e)})}const errores:string[]=[];const ok:any[]=[];rows.slice(0,5000).forEach((r,i)=>{const tipo=str(r.tipoIdentificacion||r['Tipo identificación']||'05'),ident=str(r.identificacion||r['Identificación']).replace(/\D/g,''),nombre=str(r.razon_social||r['Razón social / nombres']||r.razonSocial),email=str(r.email||r['Correo electrónico']).toLowerCase();if(!ident||!nombre||!email||!EMAIL.test(email)){errores.push(`Fila ${i+2}: identificación, nombre y correo válido son obligatorios.`);return;}ok.push({emisor_id:id,tipo_identificacion:tipo,identificacion:ident,razon_social:nombre,email,telefono:str(r.telefono||r['Teléfono'])||null,direccion:str(r.direccion||r['Dirección'])||null});});if(!ok.length)return reply.status(422).send({error:'No hay filas válidas.',errores});const {error}=await supabase.from('clientes').upsert(ok,{onConflict:'emisor_id,tipo_identificacion,identificacion'});if(error)return reply.status(422).send({error:error.message,errores});return reply.send({ok:true,importados:ok.length,errores:errores.slice(0,100)});});

  app.get('/proveedores/exportar',async(req:any,reply)=>{const id=str(req.query.emisorId);if(!id)return reply.status(400).send({error:'emisorId requerido'});const {data,error}=await supabase.from('proveedores').select('tipo_identificacion,identificacion,razon_social,nombre_comercial,email,telefono,direccion,activo').eq('emisor_id',id).order('razon_social');if(error)return reply.status(500).send({error:error.message});const b=await generarExcelDesdeFilas('Proveedores',[{clave:'tipo_identificacion',etiqueta:'Tipo identificación'},{clave:'identificacion',etiqueta:'Identificación'},{clave:'razon_social',etiqueta:'Razón social'},{clave:'nombre_comercial',etiqueta:'Nombre comercial'},{clave:'email',etiqueta:'Correo electrónico'},{clave:'telefono',etiqueta:'Teléfono'},{clave:'direccion',etiqueta:'Dirección'},{clave:'activo',etiqueta:'Activo'}],data||[] as any);reply.header('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').header('Content-Disposition','attachment; filename="proveedores.xlsx"');return reply.send(b);});
  app.post('/proveedores/importar',async(req:any,reply)=>{const id=str(req.body?.emisorId),b64=str(req.body?.archivoBase64);if(!id||!b64)return reply.status(400).send({error:'Emisor y archivo son obligatorios.'});let rows:any[];try{rows=await parsearExcel(Buffer.from(b64,'base64'));}catch(e){return reply.status(400).send({error:'No se pudo leer el Excel.',detalle:String(e)})}const errores:string[]=[];const ok:any[]=[];rows.slice(0,5000).forEach((r,i)=>{const tipo=str(r.tipoIdentificacion||r['Tipo identificación']||'04'),ident=str(r.identificacion||r['Identificación']).replace(/\D/g,''),nombre=str(r.razon_social||r['Razón social']||r.razonSocial),email=str(r.email||r['Correo electrónico']).toLowerCase();if(!ident||!nombre||!email||!EMAIL.test(email)){errores.push(`Fila ${i+2}: identificación, razón social y correo válido son obligatorios.`);return;}ok.push({emisor_id:id,tipo_identificacion:tipo,identificacion:ident,razon_social:nombre,nombre_comercial:str(r.nombre_comercial||r['Nombre comercial'])||null,email,telefono:str(r.telefono||r['Teléfono'])||null,direccion:str(r.direccion||r['Dirección'])||null,activo:String(r.activo??r['Activo']??'true').toLowerCase()!=='false'});});if(!ok.length)return reply.status(422).send({error:'No hay filas válidas.',errores});const {error}=await supabase.from('proveedores').upsert(ok,{onConflict:'emisor_id,tipo_identificacion,identificacion'});if(error)return reply.status(422).send({error:error.message,errores});return reply.send({ok:true,importados:ok.length,errores:errores.slice(0,100)});});
}
