import type { FastifyInstance } from 'fastify';
import { supabase } from '../db/supabase.js';
import { parsearExcel } from '../services/excel.js';
import { generarExcelRoles, generarPdfRol } from '../services/nominaReportes.js';
import { calcularNomina, cambiarEstadoNomina, contabilizarPeriodoNomina, obtenerPeriodoNomina, previsualizarNomina, registrarPagoNomina, listarPagosNomina, reversarPagoNomina } from '../services/nomina.js';

const emisor=(req:any)=>String(req.usuarioSesion?.emisorId||'');
const money=(n:any)=>Math.round((Number(n)||0)*100)/100;
const error=(reply:any,e:unknown,status=422)=>reply.status(status).send({error:e instanceof Error?e.message:String(e)});
async function pertenece(tabla:string,id:string,emisorId:string){const r=await supabase.from(tabla).select('id').eq('id',id).eq('emisor_id',emisorId).maybeSingle();if(r.error)throw new Error(r.error.message);return Boolean(r.data);}

export async function registrarRutasNomina(app:FastifyInstance){
  app.get('/contabilidad/nomina/empleados',async(req:any,reply)=>{const id=emisor(req);let q=supabase.from('nomina_empleados').select('*').eq('emisor_id',id).order('nombres');if(req.query.activo!==undefined)q=q.eq('activo',req.query.activo!=='false');const r=await q;return r.error?error(reply,r.error,500):reply.send({empleados:r.data||[]});});
  app.post('/contabilidad/nomina/empleados',async(req:any,reply)=>{const id=emisor(req),b=req.body||{};if(!b.identificacion||!b.nombres||!b.fechaIngreso||b.sueldoBase===undefined)return reply.status(400).send({error:'Identificacion, nombres, ingreso y sueldo son obligatorios.'});const payload={emisor_id:id,identificacion:String(b.identificacion).trim(),nombres:String(b.nombres).trim(),cargo:b.cargo||null,fecha_ingreso:b.fechaIngreso,fecha_salida:b.fechaSalida||null,sueldo_base:money(b.sueldoBase),iess_base:b.iessBase===undefined?null:money(b.iessBase),region:b.region||'COSTA',acumula_decimo_tercero:Boolean(b.acumulaDecimoTercero),acumula_decimo_cuarto:Boolean(b.acumulaDecimoCuarto),fondo_reserva_mensual:b.fondoReservaModalidad!=='ACUMULADO',activo:b.activo!==false,extension_conyuge:Boolean(b.extensionConyuge),porcentaje_extension:Number(b.porcentajeExtension||0),observaciones:b.observaciones||null,updated_at:new Date().toISOString()};const r=await supabase.from('nomina_empleados').insert(payload).select('*').single();return r.error?error(reply,r.error):reply.send({empleado:r.data,modo:'creado'});});
  app.patch('/contabilidad/nomina/empleados/:id',async(req:any,reply)=>{const id=emisor(req),b=req.body||{};const permitidos:any={};for(const [api,db] of Object.entries({identificacion:'identificacion',nombres:'nombres',cargo:'cargo',fechaIngreso:'fecha_ingreso',fechaSalida:'fecha_salida',sueldoBase:'sueldo_base',iessBase:'iess_base',region:'region',activo:'activo',observaciones:'observaciones'}))if(b[api]!==undefined)permitidos[db]=['sueldo_base','iess_base'].includes(db)?money(b[api]):b[api];permitidos.updated_at=new Date().toISOString();const r=await supabase.from('nomina_empleados').update(permitidos).eq('id',req.params.id).eq('emisor_id',id).select('*').single();return r.error?error(reply,r.error):reply.send({empleado:r.data,modo:'actualizado'});});
  app.delete('/contabilidad/nomina/empleados/:id',async(req:any,reply)=>{const r=await supabase.from('nomina_empleados').update({activo:false,updated_at:new Date().toISOString()}).eq('id',req.params.id).eq('emisor_id',emisor(req));return r.error?error(reply,r.error):reply.send({ok:true});});

  for(const x of [{ruta:'contratos',tabla:'nomina_contratos'},{ruta:'rubros',tabla:'nomina_rubros'},{ruta:'novedades',tabla:'nomina_novedades'},{ruta:'prestamos',tabla:'nomina_prestamos'},{ruta:'vacaciones',tabla:'nomina_vacaciones'},{ruta:'liquidaciones',tabla:'nomina_liquidaciones'},{ruta:'pagos',tabla:'nomina_pagos'},{ruta:'provisiones',tabla:'nomina_provisiones'},{ruta:'parametros',tabla:'nomina_parametros'},{ruta:'centros-costo',tabla:'centros_costo'}]){
    app.get(`/contabilidad/nomina/${x.ruta}`,async(req:any,reply)=>{let q=supabase.from(x.tabla).select('*').eq('emisor_id',emisor(req)).order('created_at',{ascending:false}).limit(Math.min(500,Number(req.query.limite||100)));if(req.query.periodo&&['nomina_novedades'].includes(x.tabla))q=q.eq('periodo',String(req.query.periodo));const r=await q;return r.error?error(reply,r.error,500):reply.send({items:r.data||[]});});
  }
  app.post('/contabilidad/nomina/novedades',async(req:any,reply)=>{const id=emisor(req),b=req.body||{};if(!await pertenece('nomina_empleados',String(b.empleadoId||''),id))return reply.status(404).send({error:'Empleado no pertenece a la empresa activa.'});const row={emisor_id:id,empleado_id:b.empleadoId,periodo:b.periodo,rubro_id:b.rubroId||null,tipo:b.tipo,valor:money(b.valor),cantidad:Number(b.cantidad||0),fecha:b.fecha||null,descripcion:b.descripcion||null,centro_costo_id:b.centroCostoId||null,idempotencia_clave:String(b.idempotenciaClave||`${b.periodo}:${b.empleadoId}:${b.tipo}:${b.referencia||crypto.randomUUID()}`),created_by:req.usuarioSesion?.userId||null};const r=await supabase.from('nomina_novedades').insert(row).select('*').single();if(r.error?.code==='23505')return reply.status(409).send({error:'La novedad ya fue registrada.'});return r.error?error(reply,r.error):reply.send({novedad:r.data});});

  app.get('/contabilidad/nomina/periodo',async(req:any,reply)=>{try{return reply.send(await obtenerPeriodoNomina(emisor(req),String(req.query.periodo||'')));}catch(e){return error(reply,e,500);}});
  app.get('/contabilidad/nomina/calcular',async(req:any,reply)=>{try{return reply.send(await obtenerPeriodoNomina(emisor(req),String(req.query.periodo||'')));}catch(e){return error(reply,e,500);}});// compatibilidad: lectura pura
  app.post('/contabilidad/nomina/previsualizar',async(req:any,reply)=>{try{return reply.send(await previsualizarNomina(emisor(req),String(req.body?.periodo||'')));}catch(e){return error(reply,e);}});
  app.post('/contabilidad/nomina/calcular',async(req:any,reply)=>{try{return reply.send(await calcularNomina(emisor(req),String(req.body?.periodo||''),req.usuarioSesion?.userId,false));}catch(e){return error(reply,e);}});
  app.post('/contabilidad/nomina/recalcular',async(req:any,reply)=>{try{return reply.send(await calcularNomina(emisor(req),String(req.body?.periodo||''),req.usuarioSesion?.userId,true));}catch(e){return error(reply,e);}});
  for(const x of [{ruta:'revisar',estado:'REVISADO'},{ruta:'aprobar',estado:'APROBADO'},{ruta:'cerrar',estado:'CERRADO'}])app.post(`/contabilidad/nomina/:id/${x.ruta}`,async(req:any,reply)=>{try{return reply.send({periodo:await cambiarEstadoNomina(emisor(req),String(req.params.id),x.estado,req.usuarioSesion?.userId,req.body?.observacion)});}catch(e){return error(reply,e);}});
  const contabilizar=async(req:any,reply:any,periodoId:string)=>{try{const z=await contabilizarPeriodoNomina(emisor(req),periodoId,req.usuarioSesion?.userId);return reply.send({ok:true,asientoId:z.id,estado:z.estado});}catch(e){return error(reply,e);}};
  app.post('/contabilidad/nomina/contabilizar',async(req:any,reply)=>contabilizar(req,reply,String(req.body?.periodoId||'')));
  app.post('/contabilidad/nomina/:id/contabilizar',async(req:any,reply)=>contabilizar(req,reply,String(req.params.id)));

  const pagar=async(req:any,reply:any,periodoId:string)=>{const b=req.body||{},fecha=b.fechaPago||b.fecha,monto=b.monto,formaPago=b.medioPago||b.formaPago,idempotencia=b.idempotencyKey||b.idempotenciaClave;if(!fecha||!monto||!formaPago||!idempotencia)return reply.status(400).send({error:'fechaPago, monto, medioPago e idempotencyKey son obligatorios.'});try{return reply.send({pago:await registrarPagoNomina(emisor(req),periodoId,{fecha:String(fecha),monto:Number(monto),formaPago:String(formaPago),referencia:b.referencia,observacion:b.observacion,idempotenciaClave:String(idempotencia)},req.usuarioSesion?.userId)});}catch(e){return error(reply,e);}};
  app.get('/contabilidad/nomina/:id/pagos',async(req:any,reply)=>{try{return reply.send({pagos:await listarPagosNomina(emisor(req),String(req.params.id))});}catch(e){return error(reply,e);}});
  app.post('/contabilidad/nomina/:id/pagos',async(req:any,reply)=>pagar(req,reply,String(req.params.id)));
  app.post('/contabilidad/nomina/pagar',async(req:any,reply)=>pagar(req,reply,String(req.body?.periodoId||'')));
  app.post('/contabilidad/nomina/pagos/:pagoId/reversar',async(req:any,reply)=>{const b=req.body||{};if(!b.fecha||!b.motivo)return reply.status(400).send({error:'fecha y motivo son obligatorios.'});try{return reply.send({pago:await reversarPagoNomina(emisor(req),String(req.params.pagoId),String(b.fecha),String(b.motivo),req.usuarioSesion?.userId)});}catch(e){return error(reply,e);}});

  app.post('/contabilidad/nomina/importar/previsualizar',async(req:any,reply)=>{try{const filas=await parsearExcel(Buffer.from(String(req.body?.archivoBase64||''),'base64')),errores:any[]=[];const tipo=String(req.body?.tipo||'EMPLEADOS');filas.forEach((f:any,i:number)=>{if(tipo==='EMPLEADOS'&&(!f.identificacion||!f.nombres||!f.fechaIngreso||!Number.isFinite(Number(f.sueldoBase))))errores.push({fila:i+2,campo:'registro',valor:f,problema:'Identificacion, nombres, fechaIngreso y sueldoBase son obligatorios.'});if(tipo==='NOVEDADES'&&(!f.empleadoId||!f.periodo||!f.tipo||Number(f.valor)<0))errores.push({fila:i+2,campo:'registro',valor:f,problema:'Empleado, periodo, tipo y valor no negativo son obligatorios.'});});return reply.send({tipo,filas,errores,valido:errores.length===0,tokenVistaPrevia:Buffer.from(JSON.stringify({tipo,filas})).toString('base64url')});}catch(e){return error(reply,e);}});
  app.post('/contabilidad/nomina/importar/confirmar',async(req:any,reply)=>{try{const data=JSON.parse(Buffer.from(String(req.body?.tokenVistaPrevia||''),'base64url').toString('utf8')),id=emisor(req);if(!Array.isArray(data.filas))throw new Error('Vista previa invalida.');let registrados=0;for(let i=0;i<data.filas.length;i++){const f=data.filas[i];if(data.tipo==='NOVEDADES'){if(!await pertenece('nomina_empleados',String(f.empleadoId),id))throw new Error(`Fila ${i+2}: empleado no pertenece a la empresa.`);const r=await supabase.from('nomina_novedades').upsert({emisor_id:id,empleado_id:f.empleadoId,periodo:f.periodo,tipo:f.tipo,valor:money(f.valor),idempotencia_clave:String(f.idempotenciaClave||`IMPORT:${f.periodo}:${f.empleadoId}:${f.tipo}:${i}`),created_by:req.usuarioSesion?.userId||null},{onConflict:'emisor_id,idempotencia_clave'});if(r.error)throw new Error(`Fila ${i+2}: ${r.error.message}`);registrados++;}}return reply.send({ok:true,registrados});}catch(e){return error(reply,e);}});

  app.get('/contabilidad/nomina/rol',async(req:any,reply)=>{const id=emisor(req),periodo=String(req.query.periodo||''),empleadoId=String(req.query.empleadoId||''),formato=String(req.query.formato||'pdf');try{const d=await obtenerPeriodoNomina(id,periodo);let rows=(d.empleados||[]).map((x:any)=>({identificacion:x.identificacion||'',nombres:x.nombres||'',cargo:x.cargo||'',sueldo:Number(x.sueldo||0),iessBase:Number(x.iess_base||0),iessPersonal:Number(x.iess_personal||0),iessPatronal:Number(x.iess_patronal||0),decimoTercero:Number(x.decimo_tercero||0),decimoCuarto:Number(x.decimo_cuarto||0),vacaciones:Number(x.vacaciones||0),fondoReserva:Number(x.fondo_reserva||0),beneficiosAcumulados:Number(x.beneficios_acumulados||0),netoPagar:Number(x.neto_pagar||0),costoEmpleador:Number(x.costo_empleador||0)}));if(empleadoId)rows=rows.filter((x:any)=>x.identificacion===empleadoId||x.empleadoId===empleadoId);if(!rows.length)return reply.status(404).send({error:'No existen roles para el filtro.'});const er=await supabase.from('emisores').select('razon_social,nombre_comercial,ruc,direccion_matriz').eq('id',id).single();if(er.error)throw new Error(er.error.message);const individual=Boolean(empleadoId),buf=formato==='excel'?await generarExcelRoles({empresa:er.data,periodo,rows,individual}):await generarPdfRol({empresa:er.data,periodo,rows,individual});reply.header('Content-Type',formato==='excel'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'application/pdf').header('Content-Disposition',`${formato==='excel'?'attachment':'inline'}; filename="rol-${periodo}.${formato==='excel'?'xlsx':'pdf'}"`);return reply.send(buf);}catch(e){return error(reply,e);}});
}
